CompanyEmployeeManagement.Web/Models/Company.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CompanyEmployeeManagement.Web.Models;

public class Company
{
    public int Id { get; set; }
    //[DisplayName("Company Name")]
    //[Column(TypeName = "nvarchar(150)")]
    [Required]
    public string CompanyName { get; set; }

    //[DisplayName("Tax Number")]
    //[Column(TypeName = "nvarchar(10)")]
    public string TaxNumber { get; set; }

    //[Column(TypeName = "nvarchar(150)")]
    //[DisplayName("Tax Office")]
    public string TaxOffice { get; set; }

    //[Column(TypeName = "nvarchar(300)")]
    public string Adresses { get; set; }

    public virtual ICollection<Employee> Employees { get; set; }

}

CompanyEmployeeManagement.Web/Models/Employee.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CompanyEmployeeManagement.Web.Models;

public class Employee
{
    public int Id { get; set; }
    //[DisplayName("Identity Number")]
    //[Column(TypeName = "nvarchar(11)")]
    [Required]
    public string IdentityNumber { get; set; }

    //[Column(TypeName = "nvarchar(50)")]
    //[DisplayName("First Name")]
    public string FirstName { get; set; }

    //[Column(TypeName = "nvarchar(50)")]
    //[DisplayName("Last Name")]
    public string LastName { get; set; }

    //[DisplayName("Company Id")]
    public int CompanyId { get; set; }

    public virtual Company Company { get; set; }

}

CompanyEmployeeManagement.Web/Models/ErrorViewModel.cs
namespace CompanyEmployeeManagement.Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CompanyEmployeeManagement.Web/Controllers/CompanyController.cs
using CompanyEmployeeManagement.Web.Context;
using CompanyEmployeeManagement.Web.Models;
using Microsoft.AspNetCore.Mvc;

namespace CompanyEmployeeManagement.Web.Controllers;

public class CompanyController : Controller
{
    private readonly ApplicationDbContext _dbContext;

    public CompanyController(ApplicationDbContext dbContext)
    {
        _dbContext = dbContext;
    }

    public IActionResult Index()
    {
        IEnumerable<Company> objCompanyList = _dbContext.Companies;
        return View(objCompanyList);
    }

    //GET
    public IActionResult Create()
    {
        return View();
    }

    //POST
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Create(Company obj)
    {
        if (obj.CompanyName == obj.TaxOffice.ToString())
        {
            ModelState.AddModelError("name", "The TaxOffice cannot exactly match the CompanyName.");
        }
        
            _dbContext.Companies.Add(obj);
            _dbContext.SaveChanges();
            TempData["success"] = "Company created successfully";
            return RedirectToAction("Index");

    }
    //GET
    public IActionResult Edit(int? id)
    {
        if (id == null || id == 0)
        {
            return NotFound();
        }
        var companyFromDb = _dbContext.Companies.Find(id);


        if (companyFromDb == null)
        {
            return NotFound();
        }

        return View(companyFromDb);
    }

    //POST
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Edit(Company obj)
    {
        if (obj.CompanyName == obj.TaxOffice.ToString())
        {
            ModelState.AddModelError("name", "The TaxOffice cannot exactly match the CompanyName.");
        }
        
            _dbContext.Companies.Update(obj);
            _dbContext.SaveChanges();
            TempData["success"] = "Company updated successfully";
            return RedirectToAction("Index");
    }

    public IActionResult Delete(int? id)
    {
        if (id == null || id == 0)
        {
            return NotFound();
        }
        var companyFromDb = _dbContext.Companies.Find(id);

        if (companyFromDb == null)
        {
            return NotFound();
        }

        return View(companyFromDb);
    }

    //POST
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public IActionResult DeletePOST(int? id)
    {
        var obj = _dbContext.Companies.Find(id);
        if (obj == null)
        {
            return NotFound();
        }

        _dbContext.Companies.Remove(obj);
        _dbContext.SaveChanges();
        TempData["success"] = "Company deleted successfully";
        return RedirectToAction("Index");

    }
}

CompanyEmployeeManagement.Web/Controllers/EmployeeController.cs
using CompanyEmployeeManagement.Web.Context;
using CompanyEmployeeManagement.Web.Models;
using Microsoft.AspNetCore.Mvc;

namespace CompanyEmployeeManagement.Web.Controllers
{
    public class EmployeeController : Controller
    {
        private readonly ApplicationDbContext _dbContext;

        public EmployeeController(ApplicationDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        public IActionResult Index()
        {
            IEnumerable<Employee> objEmployeeList = _dbContext.Employees;
            return View(objEmployeeList);
        }

        //GET
        public IActionResult Create()
        {
            return View();
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Employee obj)
        {
            if (obj.IdentityNumber == obj.CompanyId.ToString())
            {
                ModelState.AddModelError("name", "The CompanyId cannot exactly match the IdentityNumber.");
            }

            _dbContext.Employees.Add(obj);
            _dbContext.SaveChanges();
            TempData["success"] = "Employee created successfully";
            return RedirectToAction("Index");

        }
        //GET
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var employeeFromDb = _dbContext.Employees.Find(id);


            if (employeeFromDb == null)
            {
                return NotFound();
            }

            return View(employeeFromDb);
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Employee obj)
        {
            if (obj.IdentityNumber == obj.CompanyId.ToString())
            {
                ModelState.AddModelError("name", "The CompanyId cannot exactly match the IdentityNumber.");
            }

            _dbContext.Employees.Update(obj);
            _dbContext.SaveChanges();
            TempData["success"] = "Employee updated successfully";
            return RedirectToAction("Index");
        }

        //GET
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var employeeFromDb = _dbContext.Employees.Find(id);

            if (employeeFromDb == null)
            {
                return NotFound();
            }

            return View(employeeFromDb);
        }

        //POST
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePOST(int? id)
        {
            var obj = _dbContext.Employees.Find(id);
            if (obj == null)
            {
                return NotFound();
            }

            _dbContext.Employees.Remove(obj);
            _dbContext.SaveChanges();
            TempData["success"] = "Employee deleted successfully";
            return RedirectToAction("Index");

        }
    }
}

CompanyEmployeeManagement.Web/Controllers/HomeController.cs
using CompanyEmployeeManagement.Web.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace CompanyEmployeeManagement.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CompanyEmployeeManagement.Web/Views/Company/Create.cshtml
@model Company

<form method="post">
	<div class="border p-3 mt-4">
		<div class="row pb-2">
			<h2 class="text-primary">Create Company</h2>
			<hr />
		</div>
		@*<div asp-validation-summary="All"></div>*@
		<div class="mb-3">
			<label asp-for="CompanyName"></label>
			<input asp-for="CompanyName" class="form-control" />
			<span asp-validation-for="CompanyName" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="TaxNumber"></label>
			<input asp-for="TaxNumber" class="form-control" />
			<span asp-validation-for="TaxNumber" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="TaxOffice"></label>
			<input asp-for="TaxOffice" class="form-control" />
			<span asp-validation-for="TaxOffice" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="Adresses"></label>
			<input asp-for="Adresses" class="form-control" />
			<span asp-validation-for="Adresses" class="text-danger"></span>
		</div>
		<button type="submit" class="btn btn-primary" style="width:150px">Create</button>
		<a asp-controller="Company" asp-action="Index" class="btn btn-secondary" style="width:150px">
			Back to List
		</a>
	</div>
</form>

@section Scripts{
	@{
		<partial name="_ValidationScriptsPartial" />
	}
}

CompanyEmployeeManagement.Web/Views/Company/Delete.cshtml
@model Company

<form method="post" asp-action="Delete">
	<input asp-for="Id" hidden />
	<div class="border p-3 mt-4">
		<div class="row pb-2">
			<h2 class="text-primary">Delete Company</h2>
			<hr />
		</div>
		@*<div asp-validation-summary="All"></div>*@
		<div class="mb-3">
			<label asp-for="CompanyName"></label>
			<input asp-for="CompanyName" disabled class="form-control" />
		</div>
		<div class="mb-3">
			<label asp-for="TaxNumber"></label>
			<input asp-for="TaxNumber" disabled class="form-control" />
		</div>
		<div class="mb-3">
			<label asp-for="TaxOffice"></label>
			<input asp-for="TaxOffice" disabled class="form-control" />
		</div>
		<div class="mb-3">
			<label asp-for="Adresses"></label>
			<input asp-for="Adresses" disabled class="form-control" />
		</div>
		<button type="submit" class="btn btn-danger" style="width:150px">Delete</button>
		<a asp-controller="Company" asp-action="Index" class="btn btn-secondary" style="width:150px">
			Back to List
		</a>
	</div>
</form>

@section Scripts{
	@{
		<partial name="_ValidationScriptsPartial" />
	}
}

CompanyEmployeeManagement.Web/Views/Company/Edit.cshtml
@model Company

<form method="post" asp-action="Edit">
	<div class="border p-3 mt-4">
		<div class="row pb-2">
			<h2 class="text-primary">Edit Company</h2>
			<hr />
		</div>
		@*<div asp-validation-summary="All"></div>*@
		<div class="mb-3">
			<label asp-for="CompanyName"></label>
			<input asp-for="CompanyName" class="form-control" />
			<span asp-validation-for="CompanyName" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="TaxNumber"></label>
			<input asp-for="TaxNumber" class="form-control" />
			<span asp-validation-for="TaxNumber" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="TaxOffice"></label>
			<input asp-for="TaxOffice" class="form-control" />
			<span asp-validation-for="TaxOffice" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="Adresses"></label>
			<input asp-for="Adresses" class="form-control" />
			<span asp-validation-for="Adresses" class="text-danger"></span>
		</div>
		<button type="submit" class="btn btn-primary" style="width:150px">Update</button>
		<a asp-controller="Company" asp-action="Index" class="btn btn-secondary" style="width:150px">
			Back to List
		</a>
	</div>
</form>

@section Scripts{
	@{
		<partial name="_ValidationScriptsPartial" />
	}
}

CompanyEmployeeManagement.Web/Views/Company/Index.cshtml
@model IEnumerable<Company>
@{
    ViewData["Title"] = "Index";
}


<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Company List</h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="Company" asp-action="Create" class="btn btn-primary">
                <i class="bi bi-plus-circle"></i> &nbsp; Create New Company
            </a>
        </div>
    </div>
    <br /><br />

    <table class="table table-bordered table-striped" style="width:100%">
        <thead>
            <tr>
                <th>
                    Company Name
                </th>
                <th>
                    Tax Number
                </th>
                <th>
                    Tax Office
                </th>
                <th>
                    Adresses
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var obj in Model)
            {
                <tr>
                    <td width="20%">
                        @obj.CompanyName
                    </td>
                    <td width="20%">
                        @obj.TaxNumber
                    </td>
                    <td width="20%">
                        @obj.TaxOffice
                    </td>
                    <td width="40%">
                        @obj.Adresses
                    </td>
                    <td>
                        <div class="w-75 btn-group" role="group">
                            <a asp-controller="Company" asp-action="Edit" asp-route-id="@obj.Id"
                           class="btn btn-primary mx-2"> <i class="bi bi-pencil-square"></i> Edit</a>
                            <a asp-controller="Company" asp-action="Delete" asp-route-id="@obj.Id"
                           class="btn btn-danger mx-2"> <i class="bi bi-trash-fill"></i> Delete</a>
                        </div>
                    </td>
                </tr>
            }
        </tbody>

    </table>
</div>

CompanyEmployeeManagement.Web/Views/Employee/Create.cshtml
@model Employee

<form method="post">
	<div class="border p-3 mt-4">
		<div class="row pb-2">
			<h2 class="text-primary">Create Employee</h2>
			<hr />
		</div>
		@*<div asp-validation-summary="All"></div>*@
		<div class="mb-3">
			<label asp-for="IdentityNumber"></label>
			<input asp-for="IdentityNumber" class="form-control" />
			<span asp-validation-for="IdentityNumber" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="FirstName"></label>
			<input asp-for="FirstName" class="form-control" />
			<span asp-validation-for="FirstName" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="LastName"></label>
			<input asp-for="LastName" class="form-control" />
			<span asp-validation-for="LastName" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="CompanyId"></label>
			<input asp-for="CompanyId" class="form-control" />
			<span asp-validation-for="CompanyId" class="text-danger"></span>
		</div>
		<button type="submit" class="btn btn-primary" style="width:150px">Create</button>
		<a asp-controller="Employee" asp-action="Index" class="btn btn-secondary" style="width:150px">
			Back to List
		</a>
	</div>
</form>

@section Scripts{
	@{
		<partial name="_ValidationScriptsPartial" />
	}
}

CompanyEmployeeManagement.Web/Views/Employee/Delete.cshtml
@model Employee

<form method="post" asp-action="Delete">
	<input asp-for="Id" hidden />
	<div class="border p-3 mt-4">
		<div class="row pb-2">
			<h2 class="text-primary">Delete Employee</h2>
			<hr />
		</div>
		@*<div asp-validation-summary="All"></div>*@
		<div class="mb-3">
			<label asp-for="IdentityNumber"></label>
			<input asp-for="IdentityNumber" disabled class="form-control" />
		</div>
		<div class="mb-3">
			<label asp-for="FirstName"></label>
			<input asp-for="FirstName" disabled class="form-control" />
		</div>
		<div class="mb-3">
			<label asp-for="LastName"></label>
			<input asp-for="LastName" disabled class="form-control" />
		</div>
		<div class="mb-3">
			<label asp-for="CompanyId"></label>
			<input asp-for="CompanyId" disabled class="form-control" />
		</div>
		<button type="submit" class="btn btn-danger" style="width:150px">Delete</button>
		<a asp-controller="Employee" asp-action="Index" class="btn btn-secondary" style="width:150px">
			Back to List
		</a>
	</div>
</form>

@section Scripts{
	@{
		<partial name="_ValidationScriptsPartial" />
	}
}

CompanyEmployeeManagement.Web/Views/Employee/Edit.cshtml
@model Employee

<form method="post" asp-action="Edit">
	<div class="border p-3 mt-4">
		<div class="row pb-2">
			<h2 class="text-primary">Edit Employee</h2>
			<hr />
		</div>
		@*<div asp-validation-summary="All"></div>*@
		<div class="mb-3">
			<label asp-for="IdentityNumber"></label>
			<input asp-for="IdentityNumber" class="form-control" />
			<span asp-validation-for="IdentityNumber" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="FirstName"></label>
			<input asp-for="FirstName" class="form-control" />
			<span asp-validation-for="FirstName" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="LastName"></label>
			<input asp-for="LastName" class="form-control" />
			<span asp-validation-for="LastName" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="CompanyId"></label>
			<input asp-for="CompanyId" class="form-control" />
			<span asp-validation-for="CompanyId" class="text-danger"></span>
		</div>
		<button type="submit" class="btn btn-primary" style="width:150px">Update</button>
		<a asp-controller="Employee" asp-action="Index" class="btn btn-secondary" style="width:150px">
			Back to List
		</a>
	</div>
</form>

@section Scripts{
	@{
		<partial name="_ValidationScriptsPartial" />
	}
}

CompanyEmployeeManagement.Web/Views/Employee/Index.cshtml
@model IEnumerable<Employee>
@{
    ViewData["Title"] = "Index";
}


<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Employee List</h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="Employee" asp-action="Create" class="btn btn-primary">
                <i class="bi bi-plus-circle"></i> &nbsp; Create New Employee
            </a>
        </div>
    </div>
    <br /><br />

    <table class="table table-bordered table-striped" style="width:100%">
        <thead>
            <tr>
                <th>
                    Identity Number
                </th>
                <th>
                    First Name
                </th>
                <th>
                    Last Name
                </th>
                <th>
                    Company Id
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var obj in Model)
            {
                <tr>
                    <td width="30%">
                        @obj.IdentityNumber
                    </td>
                    <td width="30%">
                        @obj.FirstName
                    </td>
                    <td width="30%">
                        @obj.LastName
                    </td>
                    <td width="10%">
                        @obj.CompanyId
                    </td>
                    <td>
                        <div class="w-75 btn-group" role="group">
                            <a asp-controller="Employee" asp-action="Edit" asp-route-id="@obj.Id"
                           class="btn btn-primary mx-2"> <i class="bi bi-pencil-square"></i> Edit</a>
                            <a asp-controller="Employee" asp-action="Delete" asp-route-id="@obj.Id"
                           class="btn btn-danger mx-2"> <i class="bi bi-trash-fill"></i> Delete</a>
                        </div>
                    </td>
                </tr>
            }
        </tbody>

    </table>
</div>

CompanyEmployeeManagement.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

CompanyEmployeeManagement.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CompanyEmployeeManagement.Web</title>
    <link rel="stylesheet" href="~/css/bootswatchTheme.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CompanyEmployeeManagement.Web.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">Navbar</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor01">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Company" asp-action="Index">Company</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Employee" asp-action="Index">Employee</a>
                        </li>
                        @*<li class="nav-item">
                              <a class="nav-link" href="#">About</a>
                              </li>
                              <li class="nav-item dropdown">
                              <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Dropdown</a>
                              <div class="dropdown-menu">
                              <a class="dropdown-item" href="#">Action</a>
                              <a class="dropdown-item" href="#">Another action</a>
                              <a class="dropdown-item" href="#">Something else here</a>
                              <div class="dropdown-divider"></div>
                              <a class="dropdown-item" href="#">Separated link</a>
                              </div>
                              </li>*@
                    </ul>
                    <form class="d-flex">
                        <input class="form-control me-sm-2" type="text" placeholder="Search">
                        <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
                    </form>
                </div>
            </div>
        </nav>

    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class=" footer text-muted bg-dark">
        <div class="container">
            &copy; 2022 - CompanyEmployeeManagement.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>